# Generated by Django 3.2.7 on 2021-11-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
